---
role_name_check: 1
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:

  - name: nginx_balancer-01
    image: "nmusatti/ubuntu2204-pys-systemd"
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory.yml
      
verifier:
  name: ansible